import { getCurrentOrg, runScoped } from "@/src/lib/tenancy";
import { assertSubscriptionActive } from "@/src/lib/subscription";
function AddSupplierForm() {
  return (<details><summary className="cursor-pointer rounded-lg bg-blue-600 px-4 py-2 text-sm font-medium text-white hover:bg-blue-700 inline-block">+ Add Supplier</summary><form action="/api/suppliers" method="POST" className="mb-6 mt-4 space-y-3 rounded-xl border border-gray-200 bg-white p-4"><div><label className="block text-sm">Name *</label><input required type="text" name="name" className="mt-1 w-full rounded-lg border px-3 py-2 text-sm" /></div><div><label className="block text-sm">Contact Name</label><input type="text" name="contact_name" className="mt-1 w-full rounded-lg border px-3 py-2 text-sm" /></div><div><label className="block text-sm">Contact Email</label><input type="email" name="contact_email" className="mt-1 w-full rounded-lg border px-3 py-2 text-sm" /></div><button type="submit" className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-medium text-white">Add</button></form></details>);
}
export default async function SuppliersPage() {
  const org = await getCurrentOrg(); await assertSubscriptionActive(org.organization_id);
  const suppliers = await runScoped(c => c.query(`SELECT s.id, s.name, s.contact_email, s.contact_name, count(c.id) AS cert_count, count(c.id) FILTER (WHERE c.status = 'expired') AS expired_count, count(c.id) FILTER (WHERE c.status = 'expiring_soon') AS expiring_count FROM suppliers s LEFT JOIN certificates c ON c.supplier_id = s.id GROUP BY s.id, s.name, s.contact_email, s.contact_name ORDER BY s.name`).then(r => r.rows));
  return (<div><div className="flex items-center justify-between"><h1 className="text-2xl font-bold">Suppliers</h1><AddSupplierForm /></div><table className="mt-6 w-full text-sm"><thead className="border-b bg-gray-50 text-left text-gray-500"><tr><th className="px-4 py-3">Name</th><th className="px-4 py-3">Contact</th><th className="px-4 py-3">Certs</th><th className="px-4 py-3">Expiring</th><th className="px-4 py-3">Expired</th></tr></thead><tbody className="divide-y divide-gray-100">{suppliers.length === 0 ? <tr><td colSpan={5} className="px-4 py-8 text-center text-gray-400">No suppliers yet.</td></tr> : suppliers.map((s: any) => <tr key={s.id} className="hover:bg-gray-50"><td className="px-4 py-3 font-medium">{s.name}</td><td className="px-4 py-3">{s.contact_email ?? "—"}</td><td className="px-4 py-3">{s.cert_count}</td><td className="px-4 py-3">{s.expiring_count > 0 ? <span className="rounded-full bg-amber-100 px-2 py-0.5 text-xs text-amber-700">{s.expiring_count}</span> : "0"}</td><td className="px-4 py-3">{s.expired_count > 0 ? <span className="rounded-full bg-red-100 px-2 py-0.5 text-xs text-red-700">{s.expired_count}</span> : "0"}</td></tr>)}</tbody></table></div>);
}
