import { getCurrentOrg, runScoped } from "@/src/lib/tenancy";
import { assertSubscriptionActive } from "@/src/lib/subscription";
function AddCertificateForm({ suppliers }: { suppliers: { id: string; name: string }[] }) {
  return (<details className="mt-4"><summary className="cursor-pointer rounded-lg bg-blue-600 px-4 py-2 text-sm font-medium text-white hover:bg-blue-700 inline-block">+ Add Certificate</summary><form action="/api/certificates" method="POST" className="mt-4 space-y-3 rounded-xl border border-gray-200 bg-white p-4"><div><label className="block text-sm font-medium text-gray-700">Supplier *</label><select required name="supplier_id" className="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2 text-sm"><option value="">Select…</option>{suppliers.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select></div><div><label className="block text-sm font-medium text-gray-700">Type *</label><input required type="text" name="certificate_type" className="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2 text-sm" /></div><div><label className="block text-sm font-medium text-gray-700">Issuing Body</label><input type="text" name="issuing_body" className="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2 text-sm" /></div><div className="grid grid-cols-2 gap-4"><div><label className="block text-sm">Issue Date</label><input type="date" name="issue_date" className="mt-1 w-full rounded-lg border px-3 py-2 text-sm" /></div><div><label className="block text-sm">Expiry *</label><input required type="date" name="expiry_date" className="mt-1 w-full rounded-lg border px-3 py-2 text-sm" /></div></div><button type="submit" className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-medium text-white">Add</button></form></details>);
}
export default async function CertificatesPage() {
  const org = await getCurrentOrg(); await assertSubscriptionActive(org.organization_id);
  const [certs, suppliers] = await Promise.all([runScoped(c => c.query(`SELECT c.id, c.certificate_type, c.certificate_number, c.issuing_body, c.issue_date, c.expiry_date, c.status, s.name AS supplier_name FROM certificates c JOIN suppliers s ON c.supplier_id = s.id ORDER BY c.status = 'expired' DESC, c.expiry_date ASC`).then(r => r.rows)), runScoped(c => c.query(`SELECT id, name FROM suppliers ORDER BY name`).then(r => r.rows))]);
  const sc: Record<string, string> = { valid: "bg-green-100 text-green-700", expiring_soon: "bg-amber-100 text-amber-700", expired: "bg-red-100 text-red-700" };
  return (<div><div className="flex items-center justify-between"><h1 className="text-2xl font-bold">Certificates</h1><div className="flex gap-3"><a href="/api/export?format=pdf" className="rounded-lg border px-4 py-2 text-sm">📄 PDF</a><a href="/api/export?format=csv" className="rounded-lg border px-4 py-2 text-sm">📊 CSV</a></div></div><AddCertificateForm suppliers={suppliers} /><table className="mt-6 w-full text-sm"><thead className="border-b bg-gray-50 text-left text-gray-500"><tr><th className="px-4 py-3">Supplier</th><th className="px-4 py-3">Type</th><th className="px-4 py-3">Number</th><th className="px-4 py-3">Issued</th><th className="px-4 py-3">Expiry</th><th className="px-4 py-3">Status</th></tr></thead><tbody className="divide-y divide-gray-100">{certs.length === 0 ? <tr><td colSpan={6} className="px-4 py-8 text-center text-gray-400">No certificates yet.</td></tr> : certs.map((c: any) => <tr key={c.id} className="hover:bg-gray-50"><td className="px-4 py-3 font-medium">{c.supplier_name}</td><td className="px-4 py-3">{c.certificate_type}</td><td className="px-4 py-3">{c.certificate_number ?? "—"}</td><td className="px-4 py-3">{c.issue_date ? new Date(c.issue_date).toLocaleDateString() : "—"}</td><td className="px-4 py-3">{c.expiry_date ? new Date(c.expiry_date).toLocaleDateString() : "—"}</td><td className="px-4 py-3"><span className={`rounded-full px-2 py-0.5 text-xs ${sc[c.status] ?? "bg-gray-100"}`}>{c.status.replace("_", " ")}</span></td></tr>)}</tbody></table></div>);
}
