import { getCurrentOrg, runScoped } from "@/src/lib/tenancy";
import { assertSubscriptionActive } from "@/src/lib/subscription";
function NewAlertRuleForm() {
  return (<details><summary className="cursor-pointer rounded-lg bg-blue-600 px-4 py-2 text-sm font-medium text-white hover:bg-blue-700 inline-block">Add Rule</summary><form action="/api/alert-rules" method="POST" className="mt-4 max-w-md space-y-4 rounded-xl border border-gray-200 bg-white p-4"><div><label className="block text-sm">Name *</label><input required type="text" name="name" className="mt-1 w-full rounded-lg border px-3 py-2 text-sm" /></div><div><label className="block text-sm">Days Before *</label><input required type="number" name="days_before_expiry" min="1" defaultValue="30" className="mt-1 w-full rounded-lg border px-3 py-2 text-sm" /></div><div><label className="block text-sm">Recipient *</label><input required type="email" name="recipient_email" className="mt-1 w-full rounded-lg border px-3 py-2 text-sm" /></div><button type="submit" className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-medium text-white">Create</button></form></details>);
}
export default async function AlertRulesPage() {
  const org = await getCurrentOrg(); await assertSubscriptionActive(org.organization_id);
  const rules = await runScoped(c => c.query(`SELECT id, name, days_before_expiry, recipient_email, is_active, organization_id FROM alert_rules WHERE organization_id = $1 OR organization_id IS NULL ORDER BY is_active DESC, days_before_expiry ASC`, [org.organization_id]).then(r => r.rows));
  return (<div><div className="flex items-center justify-between"><h1 className="text-2xl font-bold">Alert Rules</h1><NewAlertRuleForm /></div><table className="mt-6 w-full text-sm"><thead className="border-b bg-gray-50 text-left text-gray-500"><tr><th className="px-4 py-3">Name</th><th className="px-4 py-3">Days</th><th className="px-4 py-3">Recipient</th><th className="px-4 py-3">Active</th><th className="px-4 py-3">Scope</th></tr></thead><tbody className="divide-y divide-gray-100">{rules.length === 0 ? <tr><td colSpan={5} className="px-4 py-8 text-center text-gray-400">No rules yet.</td></tr> : rules.map((r: any) => <tr key={r.id} className="hover:bg-gray-50"><td className="px-4 py-3 font-medium">{r.name}</td><td className="px-4 py-3">{r.days_before_expiry}</td><td className="px-4 py-3">{r.recipient_email}</td><td className="px-4 py-3">{r.is_active ? <span className="rounded-full bg-green-100 px-2 py-0.5 text-xs text-green-700">Yes</span> : "No"}</td><td className="px-4 py-3 text-xs text-gray-400">{r.organization_id === null ? "Global" : "Org"}</td></tr>)}</tbody></table></div>);
}
