import { getCurrentOrg, runScoped } from "@/src/lib/tenancy";
import { assertSubscriptionActive } from "@/src/lib/subscription";
function UploadForm() {
  return (<form action="/api/uploads" method="POST" encType="multipart/form-data" className="mb-6 space-y-3 rounded-xl border border-gray-200 bg-white p-4"><h2 className="font-semibold">Upload Certificate</h2><input type="file" name="file" accept="application/pdf,image/*" required className="block w-full text-sm file:rounded-lg file:bg-blue-50 file:px-4 file:py-2 file:text-blue-700" /><button type="submit" className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-medium text-white">Upload &amp; Extract</button></form>);
}
export default async function UploadsPage() {
  const org = await getCurrentOrg(); await assertSubscriptionActive(org.organization_id);
  const uploads = await runScoped(c => c.query(`SELECT u.id, u.file_name, u.status, u.confidence, u.raw_extraction, u.created_at, s.name AS supplier_name FROM certificate_uploads u LEFT JOIN suppliers s ON u.supplier_id = s.id ORDER BY u.created_at DESC`).then(r => r.rows));
  const sc: Record<string, string> = { pending: "bg-blue-100 text-blue-700", pending_review: "bg-blue-100 text-blue-700", confirmed: "bg-green-100 text-green-700", rejected: "bg-red-100 text-red-700" };
  return (<div><h1 className="text-2xl font-bold">Uploads</h1><div className="mt-4"><UploadForm /></div><table className="mt-6 w-full text-sm"><thead className="border-b bg-gray-50 text-left text-gray-500"><tr><th className="px-4 py-3">File</th><th className="px-4 py-3">Confidence</th><th className="px-4 py-3">Supplier</th><th className="px-4 py-3">Uploaded</th><th className="px-4 py-3">Status</th><th></th></tr></thead><tbody className="divide-y divide-gray-100">{uploads.length === 0 ? <tr><td colSpan={6} className="px-4 py-8 text-center text-gray-400">No uploads yet.</td></tr> : uploads.map((u: any) => <tr key={u.id} className="hover:bg-gray-50"><td className="px-4 py-3 font-medium">{u.file_name ?? "—"}</td><td className="px-4 py-3">{u.confidence ?? u.raw_extraction?.confidence ?? "—"}</td><td className="px-4 py-3">{u.supplier_name ?? "—"}</td><td className="px-4 py-3">{new Date(u.created_at).toLocaleDateString()}</td><td className="px-4 py-3"><span className={`rounded-full px-2 py-0.5 text-xs ${sc[u.status] ?? "bg-gray-100"}`}>{u.status.replace("_", " ")}</span></td><td className="px-4 py-3">{(u.status === "pending" || u.status === "pending_review") && <a href={`/dashboard/uploads/${u.id}`} className="text-blue-600 hover:underline">Review →</a>}</td></tr>)}</tbody></table></div>);
}
