import { getCurrentOrg } from "@/src/lib/tenancy";
import { pool } from "@/src/lib/pool";
export default async function DashboardHome() {
  const org = await getCurrentOrg();
  const { rows: stats } = await pool.query(`SELECT (SELECT count(*) FROM suppliers WHERE organization_id = $1) AS supplier_count, (SELECT count(*) FROM certificates WHERE organization_id = $1) AS cert_count, (SELECT count(*) FROM certificates WHERE organization_id = $1 AND status = 'expiring_soon') AS expiring_count, (SELECT count(*) FROM certificates WHERE organization_id = $1 AND status = 'expired') AS expired_count, (SELECT count(*) FROM certificate_uploads WHERE organization_id = $1 AND status = 'pending') AS pending_count`, [org.organization_id]);
  const s = stats[0];
  const { rows: needsAttention } = await pool.query(`SELECT c.id, c.certificate_type, c.expiry_date::text, c.status, s.name AS supplier_name FROM certificates c JOIN suppliers s ON c.supplier_id = s.id WHERE c.organization_id = $1 AND c.status IN ('expiring_soon', 'expired') ORDER BY c.expiry_date ASC`, [org.organization_id]);
  const sc: Record<string, string> = { valid: "bg-green-100 text-green-700", expiring_soon: "bg-amber-100 text-amber-700", expired: "bg-red-100 text-red-700" };
  return (<div><div className="flex items-baseline justify-between"><h1 className="text-2xl font-bold">Overview</h1><p className="text-sm text-gray-500">{s.supplier_count} suppliers</p></div><div className="mt-6 grid gap-4 sm:grid-cols-3"><div className="rounded-xl border border-gray-200 bg-white p-6"><div className="text-3xl font-bold">{s.cert_count}</div><span className="rounded-full bg-green-100 px-2 py-0.5 text-xs font-medium text-green-700">valid</span></div><div className="rounded-xl border border-amber-200 bg-amber-50 p-6"><div className="text-3xl font-bold text-amber-700">{s.expiring_count}</div><span className="rounded-full bg-amber-100 px-2 py-0.5 text-xs font-medium text-amber-700">expiring soon</span></div><div className="rounded-xl border border-red-200 bg-red-50 p-6"><div className="text-3xl font-bold text-red-700">{s.expired_count}</div><span className="rounded-full bg-red-100 px-2 py-0.5 text-xs font-medium text-red-700">expired</span></div></div>{s.pending_count > 0 && <div className="mt-6 rounded-xl border border-blue-200 bg-blue-50 p-6"><p className="text-sm text-blue-700">You have <strong>{s.pending_count}</strong> upload(s) awaiting confirmation. <a href="/dashboard/uploads" className="underline">Review →</a></p></div>}<h2 className="mt-8 font-semibold">Needs attention</h2>{needsAttention.length === 0 ? <p className="mt-3 text-sm text-gray-500">Nothing expiring or expired.</p> : <div className="mt-3 rounded-xl border border-gray-200 bg-white"><ul className="divide-y divide-gray-100">{needsAttention.map((c: any) => <li key={c.id} className="flex items-center justify-between p-3"><div><div className="font-medium">{c.supplier_name} — {c.certificate_type}</div><div className="text-sm text-gray-500">Expires {c.expiry_date}</div></div><span className={`rounded-full px-2 py-1 text-xs font-medium ${sc[c.status] ?? "bg-gray-100 text-gray-600"}`}>{c.status.replace("_", " ")}</span></li>)}</ul></div>}</div>);
}
