import { getCurrentOrg, withOrgContext } from "@/src/lib/tenancy";
import { assertSubscriptionActive } from "@/src/lib/subscription";
function ConfirmUploadForm({ upload, suppliers }: { upload: any; suppliers: any[] }) {
  const raw = upload.raw_extraction || upload.extracted_data || {};
  return (<form action={`/api/uploads/${upload.id}/confirm`} method="POST" className="mt-6 space-y-4 rounded-xl border border-gray-200 bg-white p-6"><h2 className="text-lg font-semibold">Confirm Extraction</h2><div><label className="block text-sm">Supplier *</label><select required name="supplier_id" className="mt-1 w-full rounded-lg border px-3 py-2 text-sm"><option value="">Select…</option>{suppliers.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select></div><div><label className="block text-sm">Type *</label><input required type="text" name="certificate_type" defaultValue={raw.certificate_type ?? ""} className="mt-1 w-full rounded-lg border px-3 py-2 text-sm" /></div><div><label className="block text-sm">Issuing Body</label><input type="text" name="issuing_body" defaultValue={raw.issuing_body ?? ""} className="mt-1 w-full rounded-lg border px-3 py-2 text-sm" /></div><div><label className="block text-sm">Cert Number</label><input type="text" name="certificate_number" defaultValue={raw.certificate_number ?? ""} className="mt-1 w-full rounded-lg border px-3 py-2 text-sm" /></div><div className="grid grid-cols-2 gap-4"><div><label className="block text-sm">Issue Date</label><input type="date" name="issue_date" defaultValue={raw.issue_date ?? ""} className="mt-1 w-full rounded-lg border px-3 py-2 text-sm" /></div><div><label className="block text-sm">Expiry *</label><input required type="date" name="expiry_date" defaultValue={raw.expiry_date ?? ""} className="mt-1 w-full rounded-lg border px-3 py-2 text-sm" /></div></div>{raw.confidence && <p className="text-sm text-gray-500">AI confidence: <span className="font-medium">{raw.confidence}</span></p>}<div className="flex gap-3"><button type="submit" className="rounded-lg bg-green-600 px-4 py-2 text-sm font-medium text-white">✓ Confirm</button><a href={`/api/uploads/${upload.id}/reject`} className="rounded-lg border border-red-300 px-4 py-2 text-sm text-red-600">✕ Reject</a></div></form>);
}
export default async function UploadDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const org = await getCurrentOrg(); await assertSubscriptionActive(org.organization_id);
  const [upload, suppliers] = await Promise.all([withOrgContext(org.organization_id, c => c.query(`SELECT * FROM certificate_uploads WHERE id = $1`, [id]).then(r => r.rows[0])), withOrgContext(org.organization_id, c => c.query(`SELECT id, name FROM suppliers ORDER BY name`).then(r => r.rows))]);
  if (!upload) return <div className="text-gray-500">Upload not found.</div>;
  const raw = upload.raw_extraction || upload.extracted_data || {};
  return (<div><h1 className="text-2xl font-bold">Review Upload</h1><div className="mt-4 rounded-xl border border-gray-200 bg-white p-4"><p className="text-sm text-gray-600">File: {upload.file_name ?? "—"}</p><p className="text-sm text-gray-600">Status: {upload.status}</p></div>{(upload.status === "pending" || upload.status === "pending_review") ? <ConfirmUploadForm upload={upload} suppliers={suppliers} /> : <div className="mt-6 rounded-xl border p-6"><p className="text-sm">This upload has been {upload.status}.</p></div>}{raw && Object.keys(raw).length > 0 && <pre className="mt-6 text-xs text-gray-600">{JSON.stringify(raw, null, 2)}</pre>}</div>);
}
